### ISSUE TITLE
Invalid DTO created automatically

### ISSUE THREAD

**Issue by zmbq** [Scripta-Qumranica-Electronica/SQE_API#51]
In the new DTOs taken from the `sign-interpretation-updates` branch, there is a problem. The `SignInterpretationReplicateDTO` extends `SignInterpretationCreateDTO` in an illegal way - it has a nullable `attributes` property, while the original is not nullable. This is not allowed in Typescript.

For now I'm commenting out this interface.

**Comment by zmbq** [comment]
I saw we're switching to issues being reported here, so I'm using Github issues. I can move to Redmine if you want.

**Comment by Bronson-Brown-deVost** [comment]
Yeah, let's do things here on GitHub from here on out.

That is a bummer about the DTOs.  Basically `SignInterpretationCreateDTO` does not allow the `attributes` or the `rois` to be null.  With the `SignInterpretationReplicateDTO`, this was the special endpoint you wanted where we copy over the attributes and rois from the original sign interpretation unless you explicitly specify different ones.  In the C# side, I am use the `Required` attributes to achieve this and you can inherit from a class and add a `Required` attribute to a field, but you cannot (so far as I know) inherit and remove a `Required` attribute, hence the direction `SignInterpretationCreateDTO`  -> `SignInterpretationReplicateDTO`.  Any suggestions? 

 I can always get rid of the inheritance, but then that screws up some of the API methods further down the line (ones that accept either `SignInterpretationCreateDTO`  `SignInterpretationReplicateDTO`).  There are other options, but none that seem as clear and expressive as the current one.

**Comment by Bronson-Brown-deVost** [comment]
I changed the DTOs now, so this is no longer relevant.
